CREATE TRIGGER INIBINDO_VALOR_NULO_VENDA
ON VENDAS
INSTEAD OF INSERT AS
BEGIN
	INSERT INTO VENDAS
	SELECT DATA,HORA,TOTAL,FK_COD_CLI FROM INSERTED

	DECLARE @TOTAL DECIMAL (10,2)
	SELECT @TOTAL = TOTAL FROM INSERTED

	IF (@TOTAL <= 0.0)
	BEGIN ROLLBACK
		PRINT ('VENDA INIBIDA')
	END

END

