CREATE TRIGGER MOSTRAR_NOME_RAZAO
ON PRODUTOS
AFTER INSERT AS
BEGIN
	DECLARE @COD_DIST INT
	DECLARE @RAZAO_SOCIAL VARCHAR (100)
	DECLARE @NOME_FANTASIA VARCHAR (100)

	SELECT @COD_DIST = FK_COD_DIS FROM INSERTED
	SELECT @RAZAO_SOCIAL = RAZAO_SOCIAL FROM DISTRIBUIDORES WHERE COD_DIST = @COD_DIST
	SELECT @NOME_FANTASIA =NOME_FANTASIA FROM DISTRIBUIDORES WHERE COD_DIST = @COD_DIST

	PRINT @NOME_FANTASIA + ' / ' + @RAZAO_SOCIAL

END
SELECT * FROM DISTRIBUIDORES
INSERT INTO DISTRIBUIDORES (NOME_FANTASIA,RAZAO_SOCIAL,EMAIL,TELEFONE) VALUES ('DOG','CAT','dogcat@gmail.com','1239515478')
INSERT INTO PRODUTOS (DATA_VALIDADE,DESCRICAO,ESTOQUE,PRECO_CUSTO,PRECO_VENDA,FK_COD_DIS) VALUES ('2020/05/02','CAT',5,45.62,52.15,1)
SELECT * FROM PRODUTOS