CREATE TRIGGER MOSTRAR_NOME_EMAIL_CLIENTE
ON VENDAS
INSTEAD OF INSERT AS
BEGIN
	INSERT INTO VENDAS
	SELECT DATA,HORA,TOTAL,FK_COD_CLI FROM INSERTED

	DECLARE @COD_CLI INT
	DECLARE @NOME VARCHAR (100)
	DECLARE @EMAIL VARCHAR (100)

	SELECT @COD_CLI = FK_COD_CLI FROM INSERTED
	SELECT @NOME = NOME FROM CLIENTES WHERE COD_CLI = @COD_CLI
	SELECT @EMAIL = EMAIL FROM CLIENTES WHERE COD_CLI = @COD_CLI

	
	PRINT @NOME + '/' + @E_MAIL

	
END
